# -*- coding: utf-8 -*-
"""FINALAIcwCode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nhs1h8CwEnVgTdiSQWjf-mPvzLMu2pX7
"""

import numpy as np
import pandas as pd
import shap
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder, LabelEncoder, label_binarize
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc
from scipy.stats import uniform, randint

################################################################################################  Loading and reading the data
application = pd.read_csv("Credit Score Classification Dataset.csv")

################################################################################################# Preprocessing
x = application.drop('Credit Score', axis=1) #Input data
y = application['Credit Score'] #What I'm trying to predict

#There is no missing values in my dataset hence I will skip handling missing values

#Encoding = process of converting data from one format to another to make it usable by algorithms (google)
#Encoding target value y - from text to numerical
le = LabelEncoder()
y_encoded = le.fit_transform(y)

#Encoding target value x - identify categorical columns to be encoded since ML requires numerical input
categorical_cols_to_encode = x.select_dtypes(include=["object"]).columns

##Blueprint of how the data is transformed
preprocessor = ColumnTransformer( transformers=[("onehot", OneHotEncoder(handle_unknown="ignore"), categorical_cols_to_encode)],remainder="passthrough")

#Apply preprocessing to features (x)
#x_processed = preprocessor.fit_transform(x)

################################################################################################# Pipeline
#To prevent data leakage, by ensuring preprocessing steps learn only from training data, which prevents inflated, misleading results (google)
pipeline = Pipeline(steps=[("preprocessor", preprocessor),("classifier", XGBClassifier(objective="multi:softprob", eval_metric="mlogloss"))])

################################################################################################  Hyperparameter tuning and cross validation
#Blueprint for hyperparameter search - tells the search algorithm what model parameters to tune and the range or distribution of values to try for each one
#AI helped me with param_distributions
param_distributions = {
    "classifier__n_estimators": randint(50, 200), #No. of decision trees in the XGB alg.
    "classifier__max_depth": randint(3, 10), #Max depth of individual decision tree
    "classifier__learning_rate": uniform(0.01, 0.3), #Controls how much each tree's prediction impacts the final model - uniform = the uniform distrbution
    "classifier__subsample": uniform(0.6, 0.4), #Fraction of the training data randomly selected to train each individual tree
    "classifier__colsample_bytree": uniform(0.6, 0.4) #Fraction of features/ columns randomly selected to build each tree - technique to prevent overfitting
}

#Stratified k fold cross validation (cross validation averages results over multiple folds, giving trustworthy performance estimate - google)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=10)

#AI helped me create and run RandomizedSearchCV
random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_distributions,
    n_iter=50,
    scoring="roc_auc_ovr",
    cv=cv,
    verbose=1,
    random_state=10,
    n_jobs=-1
)

random_search.fit(x, y_encoded)

#Best hyperparameters from the search
best_model = random_search.best_estimator_
print("\n!!! Best hyperparameters found:")
print(random_search.best_params_)

###################################################################################################################### Plotting CM, ROC, FI, SHAP
#Predictions and probabilities using the best model
y_pred = best_model.predict(x)
y_prob = best_model.predict_proba(x)

#Confusion Matrix
cm = confusion_matrix(y_encoded, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()

#ROC Curve
plt.figure(figsize=(8, 6))
y_encoded_bin = label_binarize(y_encoded, classes=np.unique(y_encoded))
n_classes = y_encoded_bin.shape[1]

for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_encoded_bin[:, i], y_prob[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'ROC curve for class {le.classes_[i]} (area = {roc_auc:.2f})')

# Feature Importance
feature_names = best_model.named_steps["preprocessor"].get_feature_names_out(x.columns)
feature_importances = best_model.named_steps["classifier"].feature_importances_

feature_importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": feature_importances
}).sort_values("Importance", ascending=False)

plt.figure(figsize=(10, 8))
plt.barh(feature_importance_df["Feature"].head(20), feature_importance_df["Importance"].head(20))
plt.title("Top 20 Feature Importances — XGBoost")
plt.gca().invert_yaxis()
plt.show()




#SHAP - beeswarm, i researched the different models, AI helped me with the code
# --- get fitted components and feature names from the best pipeline --- #################### from here
prep = best_model.named_steps["preprocessor"]          # fitted ColumnTransformer
clf  = best_model.named_steps["classifier"]            # fitted XGBClassifier

# Feature names after the preprocessor (nice labels for SHAP)
try:
    feat_names = prep.get_feature_names_out(x.columns)
    # Optional: remove transformer prefixes like "onehot__"
    feat_names = [n.split("__", 1)[-1] for n in feat_names]
except Exception:
    # Fallback if get_feature_names_out is unavailable
    feat_names = [f"f{i}" for i in range(clf.n_features_in_)]#################### to here, added by ai



x_trans = prep.transform(x)
bg = shap.sample(x_trans, min(80, x_trans.shape[0]), random_state=10)
masker = shap.maskers.Independent(bg)

explainer = shap.Explainer(
    clf.predict_proba,
    masker,
    feature_names=feat_names,
    output_names=list(le.classes_)
)
sv = explainer(x_trans)

plt.figure(figsize=(10, 6))
shap.summary_plot(sv, features=x_trans, feature_names=feat_names, show=False)
plt.title("SHAP Summary — Global Feature Impact (XGBoost)", loc="left")
plt.tight_layout()
plt.show()